spring:
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   password: 456789
   url: jdbc:mysql:///toupiao?serverTimezone=UTC

  thymeleaf:
   encoding: UTF-8
   cache: false
   prefix: classpath:/templates/
   suffix: .html
   resources:
   static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

pagehelper:
  helperDialect: mysql
  reasonable: true
  page-size-zero: true

mybatis:
  type-aliases-package: com.vote.pojo
  #mapper-locations: classpath:com/example/dao/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true

  server:
    servlet:
      context-path: /
